"""init

Revision ID: 9c6f3a99de19
Revises: 
Create Date: 2025-09-17 09:58:02.550768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6f3a99de19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('require_100_percent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ballot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('scrutiny_id', sa.Integer(), nullable=True),
    sa.Column('selections_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ballot_assembly_id'), ['assembly_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ballot_scrutiny_id'), ['scrutiny_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vote_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('scrutiny_id', sa.Integer(), nullable=True),
    sa.Column('attendee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scrutiny_id', 'attendee_id', name='one_vote_per_round')
    )
    with op.batch_alter_table('vote_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_receipt_assembly_id'), ['assembly_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_receipt_attendee_id'), ['attendee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_receipt_scrutiny_id'), ['scrutiny_id'], unique=False)

    op.create_table('attendee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.Column('can_vote', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assembly.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendee_assembly_id'), ['assembly_id'], unique=False)

    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('office', sa.String(length=40), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assembly.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_assembly_id'), ['assembly_id'], unique=False)

    op.create_table('scrutiny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('office', sa.String(length=40), nullable=True),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('min_choices', sa.Integer(), nullable=True),
    sa.Column('max_choices', sa.Integer(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assembly_id'], ['assembly.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrutiny', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrutiny_assembly_id'), ['assembly_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrutiny', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrutiny_assembly_id'))

    op.drop_table('scrutiny')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_assembly_id'))

    op.drop_table('candidate')
    with op.batch_alter_table('attendee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendee_assembly_id'))

    op.drop_table('attendee')
    with op.batch_alter_table('vote_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_receipt_scrutiny_id'))
        batch_op.drop_index(batch_op.f('ix_vote_receipt_attendee_id'))
        batch_op.drop_index(batch_op.f('ix_vote_receipt_assembly_id'))

    op.drop_table('vote_receipt')
    op.drop_table('user')
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ballot_scrutiny_id'))
        batch_op.drop_index(batch_op.f('ix_ballot_assembly_id'))

    op.drop_table('ballot')
    op.drop_table('assembly')
    # ### end Alembic commands ###
